# Generated by Django 3.2.15 on 2022-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='date',
            field=models.DateField(default='2022-11-10'),
            preserve_default=False,
        ),
    ]
